title: EL-BLOG-MUSICAL
description: musica 
permalink: ':title/'
baseurl: "/" 
url: "https://el-blog-musical.github.io" 
site-twitter: 


author: EL-BLOG-MUSICAL  
author-img: descarga.png  
about-author: Sobre musica rock y artistas 
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
